amcl:
  ros__parameters:
    use_sim_time: false
    base_frame_id: base_link
    odom_frame_id: odom
    global_frame_id: map
    tf_broadcast: true

    scan_topic: scan_cropped

    min_particles: 500
    max_particles: 2000
    kld_err: 0.05
    kld_z: 0.99

    laser_model_type: likelihood_field
    laser_likelihood_max_dist: 2.0
    laser_z_hit: 0.9
    laser_z_rand: 0.05
    laser_sigma_hit: 0.2

    odom_model_type: diff
    odom_alpha1: 0.2
    odom_alpha2: 0.2
    odom_alpha3: 0.2
    odom_alpha4: 0.2

    update_min_a: 0.2
    update_min_d: 0.25
    resample_interval: 2
